apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuisis
  labels:
    app: nginx
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: yuisis
  replicas: 1
  template:
    metadata:
      labels:
        app: yuisis
    spec:
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      containers:
      - name: yuisis
        image: ghcr.io/sphiria/yuisis:aacdbc6147fcde7b990360406531145a9e3fdbf2
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
        ports:
          - containerPort: 8080
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 20"]
        env:
        - name: MEDIAWIKI_NAME
          value: Granblue Fantasy Relink Wiki
        - name: MEDIAWIKI_META_NAMESPACE
          value: Granblue_Fantasy_Relink_Wiki
        - name: MEDIAWIKI_LOGO
          value: https://cdn.gbf.wiki/relink/Logo.png
        - name: MEDIAWIKI_FAVICON
          value: https://cdn.gbf.wiki/favicon.ico
        - name: MEDIAWIKI_SERVER
          value: //relink.gbf.wiki
        - name: MEDIAWIKI_DB_TYPE
          value: mysql
        - name: MEDIAWIKI_DB_SERVER
          value: 10.1.0.1
        - name: MEDIAWIKI_DB_NAME
          value: mediawiki
        - name: MEDIAWIKI_DB_USER
          value: mediawiki
        - name: MEDIAWIKI_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yuisis-secrets
              key: db-password
        - name: MEDIAWIKI_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: yuisis-secrets
              key: secret-key
        - name: MEDIAWIKI_AUTHTOKEN
          valueFrom:
            secretKeyRef:
              name: yuisis-secrets
              key: auth-token
        - name: REDIS_SERVER
          value: korwa-service:6379
        - name: AWS_S3_KEY
          valueFrom:
            secretKeyRef:
              name: yuisis-secrets
              key: s3-key
        - name: AWS_S3_SECRET
          valueFrom:
            secretKeyRef:
              name: yuisis-secrets
              key: s3-secret
        - name: AWS_S3_TOKEN
          valueFrom:
            secretKeyRef:
              name: yuisis-secrets
              key: s3-token
        - name: CLOUDFLARE_ZONE_ID
          valueFrom:
            secretKeyRef:
              name: yuisis-secrets
              key: cf-zone-id
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: yuisis-secrets
              key: cf-api-token
---
apiVersion: v1
kind: Service
metadata:
  name: yuisis-service
spec:
  type: ClusterIP
  ports:
  - name: http
    targetPort: 8080
    port: 8080
  selector:
    app: yuisis
---
apiVersion: v1
kind: Service
metadata:
  name: yuisis-fpm-service
spec:
  type: ClusterIP
  ports:
  - name: http
    targetPort: 9000
    port: 9000
  selector:
    app: yuisis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yuisis-fpm-cm
data:
  SCRIPT_FILENAME: "/index.php"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: relink-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
    nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: "yuisis-fpm-cm"
    nginx.ingress.kubernetes.io/proxy-body-size: "15M"
    nginx.ingress.kubernetes.io/forwarded-for-header: "CF-Connecting-IP"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/compute-full-forwarded-for: "true"
    nginx.ingress.kubernetes.io/enable-real-ip: "true"
    nginx.ingress.kubernetes.io/proxy-real-ip-cidr: "10.0.0.0/8,173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* /(?:docs|extensions|includes|cache|languages|maintenance|mw-config|serialized|skins|tests|vendor|images)/.*.php$ {
          deny all;
          return 403;
        }
      location ~ /.(svn|git)(/|$) {
          deny all;
        }
spec:
  ingressClassName: nginx
  rules:
    - host: relink.gbf.wiki
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: yuisis-fpm-service
          - path: /skins
            pathType: Prefix
            backend:
              service:
                name: yuisis-service
                port:
                  number: 8080
          - path: /resources
            pathType: Prefix
            backend:
              service:
                name: yuisis-service
                port:
                  number: 8080
          - path: /extensions
            pathType: Prefix
            backend:
              service:
                name: yuisis-service
                port:
                  number: 8080