apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arulumaya-pv-claim
  labels:
    app: arulumaya
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: v1
kind: Service
metadata:
  name: arulumaya-service
spec:
  type: ClusterIP
  selector:
    app: arulumaya
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arulumaya
  labels:
    app: arulumaya
spec:
  selector:
    matchLabels:
      app: arulumaya
  replicas: 1
  template:
    metadata:
      labels:
        app: arulumaya
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: arulumaya
          image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2-arm64
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
            - name: indices.memory.index_buffer_size
              value: "512mb"
          volumeMounts:
            - name: arulumaya-pv
              mountPath: /usr/share/elasticsearch/data
          resources:
            limits:
              memory: "4Gi"
              cpu: "2000m"
            requests:
              memory: "2.5Gi"
              cpu: "100m"
      volumes:
        - name: arulumaya-pv
          persistentVolumeClaim:
            claimName: arulumaya-pv-claim
