apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    product: k8s-elastic
  name: elastic-config
data:
  elasticsearch.yaml: |
    discovery.type: single-node
---
apiVersion: v1
kind: Service
metadata:
  name: arulumaya-service
spec:
  type: ClusterIP
  selector:
    app: arulumaya
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arulumaya
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: arulumaya
  replicas: 1
  template:
    metadata:
      labels:
        app: arulumaya
    spec:
      containers:
      - name: arulumaya
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2-arm64
        volumeMounts:
          - name: elastic-config
            mountPath: /etc/elasticsearch/elasticsearch.yaml
            subPath: elasticsearch.yaml
      volumes:
      - name: elastic-config
        configMap:
          name: elastic-config