apiVersion: v1
kind: Service
metadata:
  name: korwa-service
spec:
  type: ClusterIP
  selector:
    app: korwa
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    maxmemory 5gb
    maxmemory-policy allkeys-lru
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: korwa
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: korwa
  replicas: 1
  template:
    metadata:
      labels:
        app: korwa
    spec:
      containers:
      - name: korwa
        image: redis:7.2.4-alpine
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        volumeMounts:
        - name: config
          mountPath: /usr/local/etc/redis/
        resources:
          limits:
            memory: "5Gi"
            cpu: "2000m"
          requests:
            memory: "2Gi"
            cpu: "100m"
      volumes:
      - name: config
        configMap:
          name: redis-config