apiVersion: v1
kind: Service
metadata:
  name: korwa-service
spec:
  type: ClusterIP
  selector:
    app: korwa
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: korwa
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: korwa
  replicas: 1
  template:
    metadata:
      labels:
        app: korwa
    spec:
      containers:
      - name: korwa
        image: redis:7.2.4-alpine
        resources:
          limits:
            memory: "5Gi"
            cpu: "2000m"
          requests:
            memory: "2Gi"
            cpu: "100m"
        env:
        - name: REDIS_ARGS
          value: "--maxmemory 5gb --maxmemory-policy allkeys-lru"