apiVersion: v1
kind: ConfigMap
metadata:
  name: jobrunner-config
data: 
  jobrunner.json : |
    {
      "groups": {
        "basic": {
          "runners": 3,
          "include": [
            "*"
          ],
          "low-priority": [
            "cirrusSearchLinksUpdate",
            "htmlCacheUpdate",
            "refreshLinks"
          ]
        }
      },
      "limits": {
        "attempts": {
          "*": 3
        },
        "claimTTL": {
          "*": 3600
        },
        "real": {
          "*": 300
        },
        "memory": {
          "*": "300M"
        }
      },
      "redis": {
        "aggregators": [
          "korwa-service"
        ],
        "queues": [
          "korwa-service"
        ]
      },
      "dispatcher": "php83 /var/www/html/maintenance/run.php runJobs --type=%(type)x --maxtime=%(maxtime)x --memory-limit=%(maxmem)x --result=json"
    }